### ISSUE TITLE
Extension broken for Alpine Docker

### ISSUE THREAD

**Issue by bbstilson** [DataDog/datadog-lambda-python#221]
## Expected Behavior

Extension can be loaded.

## Actual Behavior

Extension cannot be loaded.

## Steps to Reproduce the Problem

`Dockerfile`
```dockerfile
ARG FUNCTION_DIR="/function"

FROM python:3.9.12-alpine3.15 as build-layer

# Include global arg in this stage of the build
ARG FUNCTION_DIR

# install postgresql
RUN apk add --update --no-cache postgresql-client

# install aws lambda deps
RUN apk add --no-cache \
    autoconf \
    automake \
    build-base \
    cmake \
    libcurl \
    libexecinfo-dev \
    libpq \
    libstdc++ \
    libtool \
    make \
    musl-dev \
    postgresql-dev \
    python3-dev

# Install the function's dependencies
RUN pip install --target ${FUNCTION_DIR} awslambdaric boto3
RUN pip install --target ${FUNCTION_DIR} datadog-lambda==3.55.0

RUN mkdir -p ${FUNCTION_DIR}
COPY handler.py ${FUNCTION_DIR}

# Clean build layer
FROM python:3.9.12-alpine3.15

# This is needed at runtime by awslambdaric.
RUN apk add --no-cache libstdc++

# Include global arg in this stage of the build
ARG FUNCTION_DIR
# Set working directory to function root directory
WORKDIR ${FUNCTION_DIR}

# Copy in the build dependencies.
COPY --from=build-layer ${FUNCTION_DIR} ${FUNCTION_DIR}
# Copy datadog lambda extensions.
COPY --from=public.ecr.aws/datadog/lambda-extension:21 /opt/extensions/ /opt/extensions

# https://docs.datadoghq.com/serverless/installation/python?tab=containerimage
ENV DD_TRACE_ENABLED="true"
ENV DD_API_KEY="asdfasdf"

ENTRYPOINT [ "/usr/local/bin/python", "-m", "awslambdaric" ]
CMD [ "handler.handler" ]
```

Build and run the image:
```bash
docker build -t handler:latest . && docker run  -v ~/.aws-lambda-rie:/aws-lambda -p 9000:8080 \                       
  --entrypoint /aws-lambda/aws-lambda-rie handler:latest python -m awslambdaric handler.handler
```

Invoke the function in another window:

```bash
curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'
```

If I comment out this line, the execution runs as expected:

```dockerfile
COPY --from=public.ecr.aws/datadog/lambda-extension:21 /opt/extensions/ /opt/extensions
```

## Specifications

  - Datadog Lambda Layer version: 3.55.0
  - Python version:  3.9.12
  
## Stacktrace

  ```
05 Apr 2022 01:36:24,150 [INFO] (rapid) extensionsDisabledByLayer(/opt/disable-extensions-jwigqn8j) -> stat /opt/disable-extensions-jwigqn8j: no such file or directory
START RequestId: 00e01e91-1466-436e-8b6b-a5d1d5ccca3e Version: $LATEST
05 Apr 2022 01:36:24,150 [WARNING] (rapid) First fatal error stored in appctx: Extension.LaunchError
05 Apr 2022 01:36:24,150 [ERROR] (rapid) Init failed error=fork/exec /opt/extensions/datadog-agent: no such file or directory InvokeID=
05 Apr 2022 01:36:24,150 [WARNING] (rapid) Reset initiated: ReserveFail
05 Apr 2022 01:36:24,150 [WARNING] (rapid) Runtime not started
05 Apr 2022 01:36:24,150 [WARNING] (rapid) Agent datadog-agent (e52ba34f-d6bb-4623-9a54-aaeb3f9c1daa) failed not launched; skipping shutdown
05 Apr 2022 01:36:24,150 [WARNING] (rapid) First fatal error stored in appctx: Extension.LaunchError
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x65c599]

goroutine 19 [running]:
go.amzn.com/lambda/core.(*Runtime).Release(...)
	/LambdaRuntimeLocal/lambda/core/states.go:109
go.amzn.com/lambda/rapid.doInvoke.func1.2({0x768738, 0xc000128280})
	/LambdaRuntimeLocal/lambda/rapid/start.go:328 +0x339
go.amzn.com/lambda/telemetry.(*NoOpTracer).CaptureInvokeSubsegment(0xc00010f410, {0x768738, 0xc000128280}, 0x0)
	/LambdaRuntimeLocal/lambda/telemetry/tracer.go:54 +0x2c
go.amzn.com/lambda/rapid.doInvoke.func1({0x768738, 0xc000128280})
	/LambdaRuntimeLocal/lambda/rapid/start.go:309 +0x5d0
go.amzn.com/lambda/telemetry.(*NoOpTracer).CaptureInvokeSegment(0x18, {0x768738, 0xc000128280}, 0x0)
	/LambdaRuntimeLocal/lambda/telemetry/tracer.go:44 +0x2c
go.amzn.com/lambda/rapid.doInvoke({0x768738, 0xc000128280}, 0xc0001586e0, 0xc000126600, 0xc00020e000, 0xc000138300)
	/LambdaRuntimeLocal/lambda/rapid/start.go:276 +0x219
go.amzn.com/lambda/rapid.handleInvoke({0x768738, 0xc000128280}, 0xc0001586e0, 0x0, 0xc00020e000)
	/LambdaRuntimeLocal/lambda/rapid/start.go:529 +0x345
go.amzn.com/lambda/rapid.start({0x768738, 0xc000128280}, 0xc0001586e0)
	/LambdaRuntimeLocal/lambda/rapid/start.go:690 +0x585
go.amzn.com/lambda/rapid.Start(0xc000190000)
	/LambdaRuntimeLocal/lambda/rapid/sandbox.go:72 +0xe10
go.amzn.com/lambda/rapidcore.(*SandboxBuilder).Create(0xc0001001e0)
	/LambdaRuntimeLocal/lambda/rapidcore/sandbox.go:209 +0xfd
created by main.main
	/LambdaRuntimeLocal/cmd/aws-lambda-rie/main.go:46 +0x1b2

  ```

**Comment by maxday** [comment]
👋  @bbstilson 

Thanks for your very detailed issue.
To reproduce on my end I would need to know what's inside `~/.aws-lambda-rie` and how you installed the runtime interface emulator.
Also, any reason not to use the python 3.9 AWS-provided base image : `FROM public.ecr.aws/lambda/python:3.9` ?
This image comes with the RIE so you can also test locally

**Comment by bbstilson** [comment]
Hey @maxday  thanks for the quick response! 

I followed the instructions [here](https://docs.aws.amazon.com/lambda/latest/dg/images-test.html#images-test-add) to download the rie:

```bash
mkdir -p ~/.aws-lambda-rie && curl -Lo ~/.aws-lambda-rie/aws-lambda-rie \
https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie \
&& chmod +x ~/.aws-lambda-rie/aws-lambda-rie     
```

>Also, any reason not to use the python 3.9 AWS-provided base image : FROM public.ecr.aws/lambda/python:3.9 ?
This image comes with the RIE so you can also test locally

I wanted to base the image on alpine, which isn't what is used as a base for those public images sadly 😕 

Let me know if I can provide any more details!

**Comment by bbstilson** [comment]
I'm not sure if this is related, but there's this line in the [documentation](https://docs.datadoghq.com/serverless/installation/python?tab=containerimage#configuration):

>Note that the minor version of the datadog-lambda package always matches the layer version. For example, datadog-lambda v0.5.0 matches the content of layer version 5

But I'm not sure it's true anymore since I'm seeing [versions](https://pypi.org/project/datadog-lambda/#history) going up to 55 and there isn't one for 21, which is the latest layer version.

**Comment by silvervest** [comment]
FWIW I was facing this myself and resolved it by adding the following to my Dockerfile
```
RUN apk add libc6-compat
ENV DD_LOGS_ENABLED=false
```

libc6-compat helps the libc-compiled go binary run, and for some reason if I don't disable log collection, it just sits there and times out actually running the handler. Hope this helps!

**Comment by astuyve** [comment]
Hi! We recently released alpine support for the Datadog Lambda Extension, you can grab it with version `47-alpine` or `latest-alpine` tags:
`COPY --from=public.ecr.aws/datadog/lambda-extension:47-alpine /opt/extensions/ /opt/extensions`

Thanks!
