### ISSUE TITLE
`NoneType` object has no attribute 'items'

### ISSUE THREAD

**Issue by ddhanak** [DataDog/datadog-lambda-python#249]
## Expected Behavior
Triggering a lambda through an API Gateway without providing headers should not throw an error. 

## Actual Behavior
There is an error thrown when trying to extract the headers from the context.

## Steps to Reproduce the Problem

  1. Send a request using a lambda backed API Gateway endpoint (done through console) without providing headers
  1. Check cloudwatch logs

## Specifications

  - Datadog Lambda Layer version: 62
  - Python version: 3.9
  
## Stacktrace
  
  ```
  2022-09-12T10:37:18.731-04:00	Traceback (most recent call last):
	2022-09-12T10:37:18.731-04:00	File "/opt/python/lib/python3.9/site-packages/datadog_lambda/wrapper.py", line 167, in _before
	2022-09-12T10:37:18.731-04:00	dd_context, trace_context_source = extract_dd_trace_context(
	2022-09-12T10:37:18.731-04:00
File "/opt/python/lib/python3.9/site-packages/datadog_lambda/tracing.py", line 342, in extract_dd_trace_context
	File "/opt/python/lib/python3.9/site-packages/datadog_lambda/tracing.py", line 342, in extract_dd_trace_context
	2022-09-12T10:37:18.731-04:00	) = extract_context_from_http_event_or_context(event, lambda_context)
	2022-09-12T10:37:18.731-04:00
File "/opt/python/lib/python3.9/site-packages/datadog_lambda/tracing.py", line 178, in extract_context_from_http_event_or_context
	File "/opt/python/lib/python3.9/site-packages/datadog_lambda/tracing.py", line 178, in extract_context_from_http_event_or_context
	2022-09-12T10:37:18.731-04:00	lowercase_headers = {k.lower(): v for k, v in headers.items()}
	2022-09-12T10:37:18.731-04:00	AttributeError: 'NoneType' object has no attribute 'items'
  ```

**Comment by sfirrin** [comment]
Thanks a lot for your report @ddhanak, that PR should fix the issue.

I didn't mean to close this until it's released, I'm not able to do the release so my colleague is going to release in the next few hours and I will ping you here and close the issue then.

**Comment by ddhanak** [comment]
Awesome @sfirrin !

**Comment by sfirrin** [comment]
Hi @ddhanak, sorry for the delay, we are having an issue creating the release that we are working on resolving now

**Comment by sfirrin** [comment]
@ddhanak it's now released in https://github.com/DataDog/datadog-lambda-python/releases/tag/v64 so I'm going to close this out

Thanks again for opening the issue and please let us know if you're running into anything else
