### ISSUE TITLE
Exception when lambda is triggered by EventBridge Scheduler

### ISSUE THREAD

**Issue by akbisw** [DataDog/datadog-lambda-python#275]
## Expected Behavior
No exceptions

## Actual Behavior

Exception thrown

## Steps to Reproduce the Problem

  1. Use the new EventBridge Scheduler to invoke lambda function

## Specifications

  - Datadog Lambda Layer version: 4.64.0
  - Python version: 3.9
  
## Stacktrace
  
```
Traceback (most recent call last):
File "/var/lang/lib/python3.9/site-packages/datadog_lambda/wrapper.py", line 165, in _before
self.trigger_tags = extract_trigger_tags(event, context)
File "/var/lang/lib/python3.9/site-packages/datadog_lambda/trigger.py", line 297, in extract_trigger_tags
event_source = parse_event_source(event)
File "/var/lang/lib/python3.9/site-packages/datadog_lambda/trigger.py", line 141, in parse_event_source
cw_event_categories = event_detail and event_detail.get("EventCategories")
AttributeError: 'str' object has no attribute 'get'

Traceback (most recent call last):
File "/var/lang/lib/python3.9/site-packages/datadog_lambda/wrapper.py", line 199, in _after
status_code = extract_http_status_code_tag(self.trigger_tags, self.response)
AttributeError: '_LambdaDecorator' object has no attribute 'trigger_tags'
```

**Comment by astuyve** [comment]
Hi @akbisw - I'm having a bit of trouble reproducing this, but I just realized I had tested with python 3.8:
<img width="936" alt="image" src="https://user-images.githubusercontent.com/1598537/205726522-6b082356-f4a6-4ea2-abf6-d0d00ae1d7e2.png">
Will test 3.9 and report.

**Comment by DylanLovesCoffee** [comment]
@akbisw I believe I was able to reproduce by modifying my target payload
