### ISSUE TITLE
The aws_lambda patch module can't handle callable object event handlers

### ISSUE THREAD

**Issue by michaeldimchuk** [DataDog/datadog-lambda-python#303]
NOTE: I'll be cross-posting this in the ddtrace library (https://github.com/DataDog/dd-trace-py/issues/5284) project because I'm not sure whether this is in the domain of the Lambda layer or this library itself. This could either be solved in this library by checking if the function being wrapped is a callable class instance, or by the Lambda layer passing the `__call__` function reference instead of the callable class.

## Expected Behavior
The patch_all operation should not fail, and either [ddtrace.internal.wrapping.wrap](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/internal/wrapping.py#L417) should account for callable classes, or `datadog_lambda` should be figuring out that the handler is a callable class instance and passing the `__call__` function reference instead of the class instance.

## Actual Behavior
The issue stems from ddtrace (specifically the aws_lambda module) trying to patch the outer most Lambda handlers, which can be any callable that accepts an event and context arguments, so either a standard function or a callable object, like a class instance that defines `__call__`.

The internal wrapper is passed the class instance itself instead of the `__call__` function however, so as a result, it fails as a class instance isn't going to have a `__code__` property. The patch_all the Lambda layer is executing is in a try/catch block and only runs once, so there's no errors being raised, but on every cold start there's this stack trace popping up in the logs. 

## Steps to Reproduce the Problem
Deploy a lambda function where the event handler is a callable class instance, whether through the [chalice](https://github.com/aws/chalice) framework or something like this:
```
# app.py
from typing import Any

class LambdaHandler:
    def __call__(self, event: dict[str, Any], context: Any) -> dict[str, Any]:
        return {"hello": "world"}

app = LambdaHandler()
```
With `app.app` being the handler of the lambda function.

## Specifications
Platform: AWS Lambda
Runtime: Python 3.9
Serverless Framework Version: 3.28.0
Serverless Plugin Version: 5.20.0
DataDog Lambda Layer Version: 68
ddtrace Version: 1.9.1
  
## Stacktrace
```
Traceback (most recent call last):
	File "/opt/python/lib/python3.9/site-packages/datadog_lambda/wrapper.py", line 177, in __init__
		patch_all()
	File "/opt/python/lib/python3.9/site-packages/datadog_lambda/patch.py", line 36, in patch_all
		patch_all_dd()
	File "/var/task/ddtrace/_monkey.py", line 190, in patch_all
		patch(raise_errors=False, **modules)
	File "/var/task/ddtrace/_monkey.py", line 230, in patch
		when_imported(module)(_on_import_factory(contrib, raise_errors=False))
	File "/var/task/ddtrace/vendor/wrapt/importer.py", line 284, in register
		register_post_import_hook(hook, name)
	File "/var/task/ddtrace/vendor/wrapt/decorators.py", line 470, in _synchronized
		return wrapped(*args, **kwargs)
	File "/var/task/ddtrace/vendor/wrapt/importer.py", line 82, in register_post_import_hook
		hook(module)
	File "/var/task/ddtrace/_monkey.py", line 155, in on_import
		imported_module.patch()
	File "/var/task/ddtrace/contrib/aws_lambda/patch.py", line 156, in patch
		wrap(handler, wrapper)
	File "/var/task/ddtrace/internal/wrapping.py", line 428, in wrap
		f.__code__,
	AttributeError: 'EventSourceHandler' object has no attribute '__code__'
```

**Comment by michaeldimchuk** [comment]
Closed as part of https://github.com/DataDog/dd-trace-py/issues/5284.
