### ISSUE TITLE
Unable to use function created using `from` constructs

### ISSUE THREAD

**Issue by juls858** [DataDog/datadog-lambda-python#305]
## Expected Behavior
I expect no errors when adding an L2 lambda construct
## Actual Behavior

```
TypeError: type of argument lambda_functions[0] must be one of (aws_cdk.aws_lambda.Function, aws_cdk.aws_lambda_nodejs.NodejsFunction, aws_cdk.aws_lambda_python_alpha.PythonFunction); got aws_cdk.aws_lambda._FunctionBaseProxy instead
```
## Steps to Reproduce the Problem
```python

        dd = Datadog(
            self,
            "Datadog",
            python_layer_version=68,
            extension_layer_version=38,
            site="datadoghq.com",
            api_key_secret_arn="arn:aws:secretsmanager:us-east-1:****:secret:DdApiKeySecret-****",
        )
        func = self.chalice.get_function("APIHandler")

        func2 = PythonFunction.from_function_arn(
                    self, id="APIHandler", function_arn=func.function_arn
                )
        dd.add_lambda_functions(
            [
                func2
            ]
        )
```
## Specifications

  - Datadog Lambda Layer version: 
  - Python version: 
  
## Stacktrace
  
  ```
Traceback (most recent call last):
  File "/Users/foo/repos/streamline-udfs/infrastructure/app.py", line 26, in <module>
    chalice_stack = ChaliceStack(
  File "/Users/foo/repos/streamline-udfs/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/foo/repos/streamline-udfs/infrastructure/stacks/chaliceapp.py", line 65, in __init__
    self._setup_datadog()
  File "/Users/foo/repos/streamline-udfs/infrastructure/stacks/chaliceapp.py", line 110, in _setup_datadog
    dd.add_lambda_functions(
  File "/Users/foo/repos/streamline-udfs/.venv/lib/python3.9/site-packages/datadog_cdk_constructs_v2/__init__.py", line 498, in add_lambda_functions
    check_type(argname="argument lambda_functions", value=lambda_functions, expected_type=type_hints["lambda_functions"])
  File "/Users/foo/repos/streamline-udfs/.venv/lib/python3.9/site-packages/typeguard/__init__.py", line 757, in check_type
    checker_func(argname, value, expected_type, memo)
  File "/Users/foo/repos/streamline-udfs/.venv/lib/python3.9/site-packages/typeguard/__init__.py", line 471, in check_sequence
    check_type('{}[{}]'.format(argname, i), v, value_type, memo)
  File "/Users/foo/repos/streamline-udfs/.venv/lib/python3.9/site-packages/typeguard/__init__.py", line 757, in check_type
    checker_func(argname, value, expected_type, memo)
  File "/Users/foo/repos/streamline-udfs/.venv/lib/python3.9/site-packages/typeguard/__init__.py", line 558, in check_union
    raise TypeError('type of {} must be one of ({}); got {} instead'.
TypeError: type of argument lambda_functions[0] must be one of (aws_cdk.aws_lambda.Function, aws_cdk.aws_lambda_nodejs.NodejsFunction, aws_cdk.aws_lambda_python_alpha.PythonFunction); got aws_cdk.aws_lambda._FunctionBaseProxy instead
  ```

**Comment by sfirrin** [comment]
Hi @juls858 thanks for opening this. We haven't yet worked on supporting Chalice with the CDK construct, would you be able to open a feature request with Datadog support https://www.datadoghq.com/support/ so that we can track this internally?
