### ISSUE TITLE
[BUG] failed to import ddtrace module psycopg

### ISSUE THREAD

**Issue by codelance** [DataDog/datadog-lambda-python#360]
## Expected Behavior
No error on lambda cold start boot

## Actual Behavior
Error printed on every cold start boot

## Steps to Reproduce the Problem
https://docs.datadoghq.com/serverless/installation/python/?tab=containerimage

## Specifications
  - datadog-lambda 4.78
  - Datadog Lambda Layer version: latest
  - Python version: 3.10
  
## Stacktrace
  
  ```
[ERROR]	2023-08-15T04:11:46.546Z		[dd.trace_id=0 dd.span_id=0]	failed to import ddtrace module 'ddtrace.contrib.psycopg' when patching on import
--
Traceback (most recent call last):
File "/var/lang/lib/python3.10/site-packages/ddtrace/_monkey.py", line 158, in on_import
imported_module = importlib.import_module(path)
File "/var/lang/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "/var/lang/lib/python3.10/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
self.loader.exec_module(module)
File "/var/lang/lib/python3.10/site-packages/datadog_lambda/cold_start.py", line 111, in wrapped_method
return original_exec_module(module)
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/var/lang/lib/python3.10/site-packages/ddtrace/contrib/psycopg/__init__.py", line 63, in <module>
from .patch import patch
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "/var/lang/lib/python3.10/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
self.loader.exec_module(module)
File "/var/lang/lib/python3.10/site-packages/datadog_lambda/cold_start.py", line 111, in wrapped_method
return original_exec_module(module)
File "/var/lang/lib/python3.10/site-packages/ddtrace/contrib/psycopg/patch.py", line 34, in <module>
psycopg_import = import_module("psycopg")
File "/var/lang/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
AttributeError: partially initialized module 'ddtrace.contrib.psycopg' has no attribute 'patch' (most likely due to a circular import)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "/var/lang/lib/python3.10/site-packages/ddtrace/vendor/wrapt/importer.py", line 177, in _exec_module
notify_module_loaded(module)
File "/var/lang/lib/python3.10/site-packages/ddtrace/vendor/wrapt/decorators.py", line 470, in _synchronized
return wrapped(*args, **kwargs)
File "/var/lang/lib/python3.10/site-packages/ddtrace/vendor/wrapt/importer.py", line 136, in notify_module_loaded
hook(module)
File "/var/lang/lib/python3.10/site-packages/ddtrace/_monkey.py", line 166, in on_import
imported_module.patch()
  ```

I have the following in my requirements.txt
```
psycopg[binary,pool]==3.1.9
psycopg2-binary==2.9.6
```

**Comment by codelance** [comment]
hello @astuyve thanks for the info. Looks like we have a hard requirement for psycopg2 so I can't just remove it. Is the dd-trace just not compatible?

**Comment by astuyve** [comment]
It is [supported](https://ddtrace.readthedocs.io/en/stable/integrations.html#module-ddtrace.contrib.psycopg) but there seems to be a bug where this [method](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/contrib/psycopg/patch.py#L34) is called recursively.

If possible, could you share a minimal dockerfile and/or serverless.yml file (or template.yaml, or whatever IAC tool you're using)?

That would help me narrow it down.

Thanks so much!

**Comment by codelance** [comment]
Here is our Dockerfile we are deploying
```
FROM public.ecr.aws/lambda/python:3.10
ENV APPROOT /var/task
WORKDIR $APPROOT

# Copy rest of the files
COPY ./requirements.txt /$APPROOT/requirements.txt
COPY ./app /$APPROOT/app

RUN pip install --no-cache-dir --upgrade -r /$APPROOT/requirements.txt
RUN pip install --no-cache-dir --upgrade datadog-lambda

COPY --from=public.ecr.aws/datadog/lambda-extension:latest /opt/extensions/ /opt/extensions
ENV DD_LAMBDA_HANDLER="app.main.handler"
ENV DD_SITE=datadoghq.com
ENV DD_TRACE_ENABLED=true
CMD ["datadog_lambda.handler.handler"]
```

**Comment by bertramr** [comment]
Any updates on this one? 
We experience a similar issue. According to this other issue https://github.com/DataDog/dd-trace-py/issues/6578 it might be resolved with removing the psycopg2 dependency, which is currently not an option for us.

**Comment by astuyve** [comment]
Hi @bertramr - can you provide an example including the dependencies you're using? Specifically if you can attach a pyproject.toml, or poetry.lock file indicating which specific versions of this library, dd-trace, and psycopg2 you're using?

Thanks!

**Comment by astuyve** [comment]
Hey folks, I'm going to close this one for now as there hasn't been any reply for a bit, and the linked issue(s) in dd-trace seem to be resolved.

Please feel free to re-open if needed.
Thanks!
