### ISSUE TITLE
Using the Datadog Lambda Extension with a Flask lambda causes [ERROR] KeyError: 'wsgi.url_scheme'

### ISSUE THREAD

**Issue by ronaldvaneede** [DataDog/datadog-lambda-python#384]
## Expected Behavior
No error

## Actual Behavior
A `[ERROR] KeyError: 'wsgi.url_scheme'` is raised.

## Steps to Reproduce the Problem

  1. Create simple python Flask lambda that uses serverless_wsgi or aws-wsgi
  2. Follow instructions on https://docs.datadoghq.com/serverless/installation/python/?tab=custom to add the layers and env vars
  1. Invoke the lamba over http (via ALB)

## Specifications

  - Datadog Lambda Layer version: 81
  - Python version: 3.9
  
## Stacktrace
  
```
[ERROR] KeyError: 'wsgi.url_scheme'
Traceback (most recent call last):
  File "/opt/python/lib/python3.9/site-packages/datadog_lambda/wrapper.py", line 214, in __call__
    self.response = self.func(event, context, **kwargs)
  File "/var/task/flask/app.py", line 1473, in __call__
    def __call__(self, environ: dict, start_response: t.Callable) -> t.Any:
  File "/opt/python/lib/python3.9/site-packages/ddtrace/contrib/aws_lambda/patch.py", line 120, in __call__
    self.response = self.func(*args, **kwargs)
  File "/var/task/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/python/lib/python3.9/site-packages/ddtrace/contrib/flask/wrappers.py", line 88, in wrapper
    return func(pin, wrapped, instance, args, kwargs)
  File "/opt/python/lib/python3.9/site-packages/ddtrace/contrib/flask/patch.py", line 371, in patched_wsgi_app
    return middleware(environ, start_response)
  File "/opt/python/lib/python3.9/site-packages/ddtrace/contrib/wsgi/wsgi.py", line 116, in __call__
    closing_iterator = self.app(environ, ctx.get_item("intercept_start_response"))
  File "/var/task/flask/app.py", line 1450, in wsgi_app
    ctx = self.request_context(environ)
  File "/var/task/flask/app.py", line 1367, in request_context
    return RequestContext(self, environ)
  File "/var/task/flask/ctx.py", line 316, in __init__
    self.url_adapter = app.create_url_adapter(self.request)
  File "/var/task/flask/app.py", line 412, in create_url_adapter
    return self.url_map.bind_to_environ(
  File "/var/task/werkzeug/routing/map.py", line 292, in bind_to_environ
    wsgi_server_name = get_host(env).lower()
  File "/var/task/werkzeug/wsgi.py", line 107, in get_host
    environ["wsgi.url_scheme"],
```

**Comment by purple4reina** [comment]
Hi @ronaldvaneede, thanks for opening this issue. I've looked into it a bit but have been unable to reproduce the issue. Could you provide some code samples for how you're defining your app?

**Comment by ronaldvaneede** [comment]
Hi, I've redone all steps and have not issue now. I probably made some stupid PEBKAC error somewhere 😅 
Sorry to bother you with this.

**Comment by astuyve** [comment]
Sounds good, thanks for following up @ronaldvaneede!
