### ISSUE TITLE
Errors During Lambda Init | ddtrace.contrib.aiopg

### ISSUE THREAD

**Issue by l-alfaro** [DataDog/datadog-lambda-python#407]
## Expected Behavior
No errors during lambda init

## Actual Behavior
Getting the following error:
> failed to import ddtrace module 'ddtrace.contrib.aiopg' when patching on import

## Steps to Reproduce the Problem

Sample Code:
```
import logging
import aiopg

LOGGER = logging.getLogger()
LOGGER.setLevel(logging.INFO)


def lambda_handler(event, context):
    LOGGER.info(event)
    LOGGER.info("Hello Datadog")

```
**Note** The `aiopg` package is stored in a lambda layer, along with other packages from `requirements.txt`
```
aiopg==1.4.0
aiohttp==3.8.4
asgiref==3.7.2
boto3==1.26.162
botocore==1.29.162
pydantic==2.5.0
pydantic-core==2.14.1
pydantic-settings==2.0.3
psycopg2-binary==2.9.6
requests==2.31.0
mongoengine==0.27.0
pandas==2.1.3
```

  1. Invoke lambda from console using Test tab
  1. Lambda will succeed but error(s) present in Cloudwatch logs

## Specifications

  - Datadog Lambda Layer version: 83
  - Python version: 3.11
  
## Stacktrace
  
  ```
INIT_START Runtime Version: python:3.11.v24 Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:a5ffc62d98071fc767e6f8abc670b5036a0f5a683f0bbc6cb1bac14de89647bf

TELEMETRY Name: datadog-agent State: Subscribed Types: [Platform, Function, Extension]
failed to import ddtrace module 'ddtrace.contrib.aiopg' when patching on import
Traceback (most recent call last):
File "/opt/python/lib/python3.11/site-packages/ddtrace/_monkey.py", line 165, in on_import
imported_module = importlib.import_module(path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/lang/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "/opt/python/lib/python3.11/site-packages/ddtrace/internal/module.py", line 211, in _exec_module
self.loader.exec_module(module)
File "/opt/python/lib/python3.11/site-packages/datadog_lambda/cold_start.py", line 111, in wrapped_method
return original_exec_module(module)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/opt/python/lib/python3.11/site-packages/ddtrace/contrib/aiopg/__init__.py", line 25, in <module>
from .patch import get_version
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "/opt/python/lib/python3.11/site-packages/ddtrace/internal/module.py", line 211, in _exec_module
self.loader.exec_module(module)
File "/opt/python/lib/python3.11/site-packages/datadog_lambda/cold_start.py", line 111, in wrapped_method
return original_exec_module(module)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/python/lib/python3.11/site-packages/ddtrace/contrib/aiopg/patch.py", line 7, in <module>
from ddtrace.contrib.aiopg.connection import AIOTracedConnection
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "/opt/python/lib/python3.11/site-packages/ddtrace/internal/module.py", line 211, in _exec_module
self.loader.exec_module(module)
File "/opt/python/lib/python3.11/site-packages/datadog_lambda/cold_start.py", line 111, in wrapped_method
return original_exec_module(module)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/python/lib/python3.11/site-packages/ddtrace/contrib/aiopg/connection.py", line 25, in <module>
class AIOTracedCursor(wrapt.ObjectProxy):
File "/opt/python/lib/python3.11/site-packages/ddtrace/contrib/aiopg/connection.py", line 33, in AIOTracedCursor
@asyncio.coroutine
^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
[ERROR] 2023-12-19T16:57:18.708Z failed to import ddtrace module 'ddtrace.contrib.aiopg' when patching on import Traceback (most recent call last): File "/opt/python/lib/python3.11/site-packages/ddtrace/_monkey.py", line 165, in on_import imported_module = importlib.import_module(path) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/var/lang/lib/python3.11/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen importlib._bootstrap>", line 1204, in _gcd_import File "<frozen importlib._bootstrap>", line 1176, in _find_and_load File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 690, in _load_unlocked File "/opt/python/lib/python3.11/site-packages/ddtrace/internal/module.py", line 211, in _exec_module self.loader.exec_module(module) File "/opt/python/lib/python3.11/site-packages/datadog_lambda/cold_start.py", line 111, in wrapped_method return original_exec_module(module) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen importlib._bootstrap_external>", line 940, in exec_module File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "/opt/python/lib/python3.11/site-packages/ddtrace/contrib/aiopg/__init__.py", line 25, in <module> from .patch import get_version File "<frozen importlib._bootstrap>", line 1176, in _find_and_load File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 690, in _load_unlocked File "/opt/python/lib/python3.11/site-packages/ddtrace/internal/module.py", line 211, in _exec_module self.loader.exec_module(module) File "/opt/python/lib/python3.11/site-packages/datadog_lambda/cold_start.py", line 111, in wrapped_method return original_exec_module(module) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/python/lib/python3.11/site-packages/ddtrace/contrib/aiopg/patch.py", line 7, in <module> from ddtrace.contrib.aiopg.connection import AIOTracedConnection File "<frozen importlib._bootstrap>", line 1176, in _find_and_load File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 690, in _load_unlocked File "/opt/python/lib/python3.11/site-packages/ddtrace/internal/module.py", line 211, in _exec_module self.loader.exec_module(module) File "/opt/python/lib/python3.11/site-packages/datadog_lambda/cold_start.py", line 111, in wrapped_method return original_exec_module(module) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/python/lib/python3.11/site-packages/ddtrace/contrib/aiopg/connection.py", line 25, in <module> class AIOTracedCursor(wrapt.ObjectProxy): File "/opt/python/lib/python3.11/site-packages/ddtrace/contrib/aiopg/connection.py", line 33, in AIOTracedCursor @asyncio.coroutine ^^^^^^^^^^^^^^^^^ AttributeError: module 'asyncio' has no attribute 'coroutine'
Configured ddtrace instrumentation for 58 integration(s). The following modules have been patched: aioredis,aiomysql,aredis,asyncio,boto,botocore,bottle,cassandra,celery,consul,django,elasticsearch,algoliasearch,futures,gevent,graphql,grpc,httpx,kafka,mongoengine,mysql,mysqldb,pymysql,mariadb,psycopg,pylibmc,pymemcache,pymongo,redis,rediscluster,requests,rq,sanic,sqlite3,aiohttp,aiohttp_jinja2,aiopg,vertica,molten,jinja2,mako,flask,flask_login,starlette,falcon,pylons,pyramid,pynamodb,pyodbc,fastapi,dogpile_cache,yaaredis,asyncpg,aws_lambda,openai,langchain,subprocess,unittest
[INFO] 2023-12-19T16:57:18.767Z Configured ddtrace instrumentation for 58 integration(s). The following modules have been patched: aioredis,aiomysql,aredis,asyncio,boto,botocore,bottle,cassandra,celery,consul,django,elasticsearch,algoliasearch,futures,gevent,graphql,grpc,httpx,kafka,mongoengine,mysql,mysqldb,pymysql,mariadb,psycopg,pylibmc,pymemcache,pymongo,redis,rediscluster,requests,rq,sanic,sqlite3,aiohttp,aiohttp_jinja2,aiopg,vertica,molten,jinja2,mako,flask,flask_login,starlette,falcon,pylons,pyramid,pynamodb,pyodbc,fastapi,dogpile_cache,yaaredis,asyncpg,aws_lambda,openai,langchain,subprocess,unittest
EXTENSION Name: datadog-agent State: Ready Events: [INVOKE, SHUTDOWN]
START RequestId: 5269fc73-9618-437c-8e94-e1e957ec2d2c Version: $LATEST
[INFO] 2023-12-19T16:57:18.771Z 5269fc73-9618-437c-8e94-e1e957ec2d2c {'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}
[INFO] 2023-12-19T16:57:18.771Z 5269fc73-9618-437c-8e94-e1e957ec2d2c Hello luke
END RequestId: 5269fc73-9618-437c-8e94-e1e957ec2d2c
  ```

**Comment by astuyve** [comment]
Hi @l-alfaro – thanks for reaching out!
It appears this error is handled and your function continues to execute, correct?

Is there missing or broken tracing? Are you using `aiopg`?

Furthermore it does seem like this error is generated from [ddtrace](github.com/datadog/dd-trace-py), and perhaps we should move this ticket there?
```
File "/opt/python/lib/python3.11/site-packages/ddtrace/contrib/aiopg/connection.py", line 33, in AIOTracedCursor
@asyncio.coroutine
^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
```

Thanks so much!

**Comment by astuyve** [comment]
Closing this as there has been no activity. Please feel free to update this ticket if necessary.
