### ISSUE TITLE
libssl3.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by john-lowry** [DataDog/datadog-lambda-python#492]
## Expected Behavior
Use Datadog Extension layer and python layer version as normal.

## Actual Behavior
{
  "errorMessage": "Unable to import module 'datadog_lambda.handler': libssl3.so: cannot open shared object file: No such file or directory",
  "errorType": "Runtime.ImportModuleError",
  "requestId": "",
  "stackTrace": []
}

## Steps to Reproduce the Problem

  1.
  Add the following to the template.yaml for my AWS SAM python lambda:
 ` Transform:
      - AWS::Serverless-2016-10-31
      - Name: DatadogServerless
        Parameters:
          stackName: !Ref "AWS::StackName"
          pythonLayerVersion: 94
          extensionLayerVersion: 58
          site: "datadoghq.com"
          apiKeySecretArn: "<removed>"`

  2. deplay with `sam deploy`

## Specifications

  - Datadog Lambda Layer version: 58
  - Python version: 94
  
## Stacktrace

ImportError: libssl3.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "./python/lib/python3.11/site-packages/datadog_lambda/handler.py", line 36, in <module>
  File "/var/lang/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "./python/lib/python3.11/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
  File "./python/lib/python3.11/site-packages/datadog_lambda/cold_start.py", line 119, in wrapped_method
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/task/function.py", line 17, in <module>
    import ldap
  File "./python/lib/python3.11/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
  File "./python/lib/python3.11/site-packages/datadog_lambda/cold_start.py", line 119, in wrapped_method
  File "/var/task/ldap/__init__.py", line 34, in <module>
    import _ldap
  File "./python/lib/python3.11/site-packages/ddtrace/internal/module.py", line 185, in _create_module
ImportError: libssl3.so: cannot open shared object file: No such file or directory

**Comment by purple4reina** [comment]
@john-lowry Hey, thanks for opening this issue. The `Unable to import module 'datadog_lambda.handler': ______` error is typically due to an error in your lambda code, in this case an inability to import `libssl3.so`. But in your case I'm not certain about this. Could you confirm for me, if you remove the Datadog python layer, does the error go away?

**Comment by astuyve** [comment]
Closing due to no response, please feel free to re-open if needed!
